import sys
ts=sys.argv[1]
line=("- "+ts+" | POWL (Powell Industries, Inc., cover 10-Q 0000080420-26-000107) | Q1 IN / Q2 OUT (on the business: every 10-K FY2009-FY2025 says the work is \"typically awarded in competitive bid situations\" and FY2007-FY2025 that ABB, Eaton, Schneider and Siemens \"may, therefore, be able to provide their products or services at lower prices\"; price fell in the trough and followed cost in the boom, no filed year credits a price rise, [E2-44] not shown; operating margin -4.9% to 9.3% in 23 of 25 filed years, 17.7-19.7% FY2024-FY2025 on a $2.4bn backlog and tight supply, [E3-43]'s \"a business\"; Eaton's electrical segments 10-20 points higher at both ends of the cycle; case for IN written first) "
"| $187.23 (2026-09-28 Nasdaq close, aggregator, flagged; regularMarketTime 16:00:00 ET) x 36,432,564 sh (one class, post the 3-for-1 split of 2026-04-01 verified against the 8-K and EX-3.1; cover_shares.py agreed) = cap $6,821.3M, no borrowings, cash $633.6M against customer advances $466.4M; sovereign 5.56% (UST 30Y par 09/28/2026, direct fetch, the tool agreed) "
"| FAIL (Q2) | 7cebe496 3f138773 0cee09bf ac866a66 2cd3ba43 33bb980b "
"| WAVE 7 name 109 of 218, register entry 251 (dispatcher re-counted from the file: heading unique at line 502, 251 entries to the write-early heading, POWL first and once, PFGC second; done file 109 lines equal to the order file's first 109; no alert and no PORTFOLIO row; alerts.json parses; reading-list fold ends \"Next in the order file: NWPX.\"; shapes index dated note only (#11 THE PASS-THROUGH signature, #20 THE WAVE feature); check_framework PASS re-run by the dispatcher). POWL in no tier roster. Deal: none (no deal-class form in the filing list, checked by hand). "
"Beneath the close, computation only: five-year owner earnings $72.4-73.2M (1.06-1.07% of cap), three-year $137.4-140.8M, TTM $238.7-242.4M, every window of three years or more -$15.3M to $140.8M; FY2023's $227.6M of customer prepayments named; about $20 a share at the floor with no growth on five years, $38 on three, $66 on the trailing year. Q3 prompts recorded not scored: EBITDA 75% of the cash incentive, the FY2025 target set below FY2024's actual and paid at 200%, the 2011 Powell Canada restatement. "
"Screen: cap_m reproduces on the 2026-09-01 close; oe_bottom_m 72, oe_top_m 141 and spread 0.945 reproduce; yields on 5.35%; -$36.1M reproduced, level notes truncated in the CSV; two years carry the window confirmed; \"9-yr OCF series\" refuted; best_year_dep 0.499 and 0.564 not reproduced; deal_note, acq_note, da_note blank and right in effect. "
"REPORTED, NOT PATCHED: NEW, wc_note cannot see a cash-flow line tagged outside us-gaap (flagged an $18.6M payables move, missed the $227.6M contract-balance swing, and dropped the sign of operating cash); recurring: deal_note TypeError and ValueError, deal_filings returned nothing, run.py growth struck against the bond and points-over -0.95 to -0.89 beside a yield 3.5 points under the bond, chartPreviousClose 13.067 meaningless, cik_for none for THR and SIEGY; EDGAR's state field NV for a Delaware registrant. Agent's own errors (seven, recorded in the run file) all corrected before the commit carrying them. Left on disk uncommitted: the agent's scratch _msg.txt and the pre-existing ARCB _logmsg_dispatch.txt, not touched. 109 remain. Next: NWPX.")
open("Screens/_daily/OVERNIGHT LOG.md","a",encoding="utf-8").write(line+"\n")
