import datetime
ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
line = ("- " + ts + " | SANM (Sanmina Corporation, cover 10-Q 0000897723-26-000037) | Q1 IN / Q2 OUT (on the business: [E2-58] commodity class in the filer's own words, the industry \"has experienced a surplus of manufacturing capacity\" and is \"extremely price sensitive\", supply agreements carry \"cost reduction objectives\", six named global competitors plus the customer's own factory, \"We may not be able to offer prices as low as some of our competitors\"; [E3-43] pricing demonstration not shown, no gross-margin explanation FY2010 to the June 2026 quarter names a price increase; gross margin 6.2-8.8% for seventeen years and a 3.7% ten-year operating margin mid-band among seven filed EMS peers, so the wide-and-sustainable cost exception is not shown either; margin widening since FY2018, 15.1% mean pre-tax return on net capital and the ZT quarter's 10.2% IMS margin written first as the strongest evidence against; reversal condition in words) "
 "| $224.77 (2026-09-25 Nasdaq close, aggregator, flagged; a $216.505 intraday print recorded, not used) x 53,597,356 sh (one class, no preferred issued) = cap $12,047.1M; sovereign 5.49% (UST 30Y par 09/25/2026, struck fresh) "
 "| FAIL (Q2) | 9b5128e3 742492ba cf0f46dc 3b73f90b d1f7d717 "
 "| WAVE 7 name 98 of 218, register entry 240 (dispatcher re-counted from the file: heading unique at line 502, 240 entries to the write-early heading, SANM first and once; done file 98 lines equal to the order file's first 98; no alert and no PORTFOLIO row; reading-list fold ends \"Next in the order file: OII.\"; check_framework PASS re-run by the dispatcher). SANM in no tier roster. "
 "Deal: the screen's blank deal_note was wrong, Sanmina bought ZT Systems from AMD, closed 2025-10-27 ($1,408M cash after a $243M settlement, 1,151,052 shares, earnout up to $450M carried at $183M), so no filed annual period holds the priced perimeter; Sanmina the buyer, the quote is not a spread. "
 "Beneath the close, computation only: owner earnings $138.5-437.8M every window FY2009-FY2025 at both (c) ends (1.15-3.63% of cap), TTM $505.4-647.9M (4.20-5.38%) carrying the collection of ZT's acquired receivables, none reaching 5.49%; negative or near zero FY2010, FY2018, FY2023. Q3 prompts recorded not scored: the 2023 Item 4.02 restatement of FY2020-FY2022, the SCI qui tam settled in principle for $5.9M, non-GAAP margin 8.0% against 6.4% GAAP. #11 THE PASS-THROUGH (commodity form) with #20 THE WAVE and #6 THE BORROWED BALANCE SHEET as features, signatures only, dated note. "
 "Screen errors: wc_note reproduces (AP 177.8% of FY2023 OCF) but reads the sign backwards (payables fell $418M and consumed the cash), and misses FY2025 where customer advances were 106.8% of OCF; cap_m 13.3% low; spread compares two windows and two ends; yield fields on the stale cap and 5.35%; \"no single-year dependence (9-yr OCF series)\" wrong on both halves (seventeen tagged, FY2025 71% of the three-year sum); window_disagree overstated; 10-K float figure does not reproduce, recorded not resolved. oe_bottom/oe_top reproduce. "
 "REPORTED, NOT PATCHED: tools/sources.price and tools/run.py took an intraday print again (third filer); NEW, run.py averages each year's low and high capex ends, mixing the ends across years and widening its bands; points_over() growth struck against the bond not the floor (fifth filer). "
 "Agent's own errors (eight drafting errors in Q2 and beneath the close; the fold script adapted from WING appended WING to the done file, caught on the verification read and repaired before commit) recorded in the run file. Brief errors recorded by the run: a dispatch time later than the lock, and the trailer model name. Left on disk uncommitted: the agent's _msg.txt and the ignored cache/. 120 remain. Next: OII.\n")
p = "Screens/_daily/OVERNIGHT LOG.md"
raw = open(p, "rb").read()
nl = b"\r\n" if b"\r\n" in raw else b"\n"
if not raw.endswith(nl): raw += nl
open(p, "wb").write(raw + line.replace("\n", "").encode("utf-8") + nl)
print(line[:80])
