import re, sys
P = 'PORTFOLIO.md'
t = open(P, encoding='utf-8').read()

anchor = '| — | ACNB |'
i = t.find(anchor)
assert i != -1, 'ACNB row not found'
j = t.find('\n', i)
assert j != -1

ROW = ('\n| — | JPM | 4.54–6.76 % pre-tax on the bank CONVENTION (three windows × the (c) band, '
 '2026-09-19; bottom boundary 4.54 %, centre 6.02 %) | 5.34 % USD | **above the sovereign on every '
 'construction once growth is added, +2.20 to +5.72 points; BELOW the ~10 % [E4-28] floor at the bottom '
 'boundary (7.54 %) and at the centre (9.62 %) — above the bond, below the floor, the fifth name on '
 'this track in that configuration after KO, CB, GFF and ACNB** | **RUN DONE** '
 '(`Test Runs/2026-09-19 Run - JPM JPMorgan Chase.md`): **Q1–Q4 all IN — the FOURTH BANK this '
 'project has run, the SECOND to clear the business gates, and the LARGEST company it has ever priced '
 '($929,488M). Q5 OUT ON PRICE.** '
 '**Q2 IN NARROW, direction MIXED, on [E2-58]’s single exception measured on the COST OF OPERATIONS '
 'and NOT on the cost of funds** — a 52 % overhead ratio against BAC 61.65 / C 64.7 / WFC 66, '
 'five-year means 55.40 / 64.66 / 67.52 / 69.20, a **9.65-point gap on a $182,447M revenue base worth '
 'about $17.6bn a year pre-tax, and WIDENING** — while **it FAILS the test ACNB passed on: third of '
 'six on the cost of total deposits in every one of five years** (5-yr means WFC 0.927 %, BAC 1.066 %, '
 '**JPM 1.202 %**), noninterest-bearing deposit share 29.1 → 24.1 %, IB fee wallet 9.1 → 8.4 %, '
 'and **domestic deposit share 12bp BELOW end-2021 after absorbing First Republic** (11.77 → 11.65 % '
 'of all FDIC-insured domestic deposits, from 4,313–4,904 filers at six dates). Five-year mean ROTCE '
 '**20.80 %, first of six in four of five years** (MS 17.66, GS 14.58, BAC 14.56, WFC 12.87, C 8.38). '
 '**[E2-59] on a dated event: JPM held 11.30 % of US domestic insured deposits at 2022-12-31, so the '
 'ordinary route to a $200bn bank was shut — the $2,775M First Republic gain was GRANTED BY THE '
 'REGIME, not won from customers.** '
 '**Q3 IN at GATE weight, decided by an artifact NAMED then OBTAINED from the issuing authority — the '
 'Federal Reserve’s own enforcement register (2,889 actions): thirteen entity actions since 2003, '
 'nine of them orders, ZERO still open, $878,932,500 of civil money penalties (the largest of the six), '
 'the 2024-03-08 order terminated 2025-12-04 — while Citigroup and Wells Fargo each still have an '
 'OPEN order.** That is [E5-22] answered by the supervisor’s own dates, and it is why the run does not '
 'reach the Citigroup-2007 conclusion. **[E3-02] tested at 2022-12-31 from the FDIC Call Reports: HTM '
 'securities at 1.40x equity — the LOWEST of seven institutions against SVB’s 5.91x and BAC’s '
 '2.81x — and assets/equity 10.5x, also the lowest.** [E2-50]: cumulative provision 2019–25 '
 '$54,408M against charge-offs $41,302M, **31.7 % MORE reserved than lost**, allowance ≥ 2.72x the '
 'next year’s charge-offs every year; **[E2-67] met in substance, NOT in form — no reserving '
 'back-test is published.** **Zero net common shares issued in five years** (issued 4,104,933,895 in all '
 'six filings read) while the count fell 12.8 %. **LIVE CAPITAL-ALLOCATION FLAG: $31,640M of buybacks in '
 '2025 at 2.57x tangible book against $9,898M at 1.65x in 2023 — three times the dollars at 1.6 times '
 'the price, under a programme that "does not establish specific price targets or timetables" '
 '([E5-24] inverted, [E5-25] declined); binds POSITION SIZE DOWN, never the rate [E4-13].** [E4-27]: the '
 'CEO’s entire equity award pays maximum at ROTCE ≥ 18 % and the five-year buyback accounts for '
 'about 3.8 points of the reported 20 %. '
 '**Q4 IN — GOOD, not great. The corpus’s own stress does not bite: 10 % of $1,542,462M of loans '
 'at 30 % severity is $46,274M against $86,807M of pre-provision profit plus a $31,531M allowance; '
 'break-even needs 5.63 % of the book (7.6x the worst filed year) and erasing tangible equity needs '
 '27.21 %. The bank’s own published result: SCB 2.5 %, the regulatory FLOOR, against a 14.2 % CET1 '
 'ratio and an 11.5 % requirement.** Strengths 3 of 3 with (3) QUALIFIED: uninsured deposits $1,743.9bn, '
 '**64.3 % of deposits against First Republic’s 67.7 %**, covered 87 % by $1.5tn of liquidity at a '
 '110 % LCR, "primarily wholesale operating deposits", and in 2023 **JPMorgan’s deposit share ROSE '
 'while three banks failed**. **NAMED DEATH — proposed shape #27 THE LICENCE: $120.9bn, 35.3 % of '
 'common equity, earns about 3.7 % in Corporate as the regulatory buffer while CIB earns 18 % on '
 '$149.5bn, CCB 32 % on $56.0bn and AWM 40 % on $16.0bn; each point of required CET1 on $1,981,692M of '
 'RWA moves $19,817M from the 18–40 % businesses into the 3.7 % one, about $2.9bn a year pre-tax, and '
 'the mix is a Federal Reserve decision. LIKELY, and it runs both ways — Corporate falls to $98.4bn '
 'on 2026-01-01.** '
 '**Q5: quit on at the floor** — value ~$200 to ~$340 a share (3.08x tangible book at the quote) vs '
 '**$349.67**; Screamer test returns the third outcome, narrowly. **Watch-list: bands $230 and $190; '
 'alerts armed 2026-09-19, TO BE RE-STRUCK ANNUALLY because tangible book compounds about 10 % a year.** '
 '**THE STRONGEST FACT AGAINST: on the record the business has DELIVERED, the price clears the floor** '
 '— diluted EPS +6.85 %/yr 2021–25 and tangible book per share +10.30 %/yr 2020 to mid-2026 '
 'against the 3.24–5.46 % of perpetual growth the quote needs. **The whole Q5 failure rests on one '
 'judgment: that the 82.5 % rise in net interest income from $52,311M (2021) to $95,443M (2025), on '
 '52.3 % of the revenue, was the federal funds rate and not the business** [E4-41, E3-51]. And the board '
 'bought 8.9M shares at **$317.28 in December 2025**, inside the top quarter of the run’s optimistic '
 'case — the disagreement is one year of multiple expansion. Live Q3 items: the **cockroach fired '
 'twice in one failure class** (the 2020 DOJ DPA over spoofing and the March 2024 OCC/Federal Reserve '
 'orders over trade-surveillance data completeness); **metric-switching — four reportable segments to '
 'three in January 2024, so Commercial Banking’s separate return series is gone [E2-56]**; and '
 '**guidance beaten on three of three measurable 2025 items** ($95,443M vs ~$94.0bn, $92,591M vs '
 '~$90.0bn, 3.31 % vs ~3.60 %), which answers [E3-48] in the company’s favour while [E5-30] keeps the '
 'practice flagged. Cap $929,488M on 2,658,186,195 cover shares (`0001628280-26-054343`); **issued '
 '4,104,933,895 less treasury 1,446,747,700 reconciles to the share, and the issued figure would have '
 'overstated the cap 1.544-fold**. |')

t = t[:j] + ROW + t[j:]
open(P, 'w', encoding='utf-8').write(t)
sys.stdout.write('JPM row inserted after ACNB: %s\n' % (t.count('| — | JPM |') == 1))
sys.stdout.write('rows in the ranked table now: %d\n' %
    len(re.findall(r'^\| ', re.search(r'## THE OPPORTUNITY SET, RANKED.*?(?=\n## )', t, re.S).group(0), re.M)))
