p='frag_q2.md'; s=open(p,encoding='utf-8').read()
R=[
("For 2026 the filer expects *\"stable pricing for ROVs\"*.",
 "**And two recent years do meet [E2-44]'s test in its mild form, stated here because it is the part of this item the answer does not dispose of:** in FY2024 the price per day rose 12.6% while days utilized fell 0.8% (61,874 → 61,382) and utilization 68% → 67%; in FY2025 it rose 6.1% while days fell 2.9% and contracted floating rigs averaged 137 against 146; and in the six months to 2026-06-30 days utilized fell again (30,382 → 28,604) with *\"higher average revenue per day in 2026, reflecting a mix of improved pricing and the impact of non-recurring\"* benefits. That is price taken in a softening market, for two and a half years, in a fleet cut by a quarter and an industry whose rig supply had shrunk. [E3-43] names that route for *\"a business\"*: *\"if supply of its product or service is tight. Tightness in supply usually does not last long.\"* The filer's own outlook for 2026 is *\"stable pricing for ROVs\"*. Two and a half years of price after six years of giving it back is not yet *\"regularly\"*; the reversal condition below asks for the test that the last cycle failed."),
("- **[E2-44] (1), tested in the years it bites.** Capacity was not fully utilized in every year from FY2015 to FY2025 (46-69%). In the six falling or flat years FY2015-FY2020 the price per day fell each year but FY2019 (+1.7%, *\"slightly improved pricing\"*). In the five years FY2021-FY2025 it rose with utilization climbing from 58% to 68% as the fleet shrank; the FY2025 rise came with utilization falling (67% → 65%) and is the one year that reads as [E2-44]'s test met. One year against six does not make *\"an ability to increase prices rather easily\"*.",
 "- **[E2-44] (1), tested in the years it bites.** Capacity was not fully utilized in any year from FY2015 to FY2025 (46-69%). In FY2015-FY2020, when rigs were being idled, the price per day fell in five of six years (FY2019 the exception, +1.7%, *\"slightly improved pricing\"*). In FY2021-FY2023 it rose as utilization climbed from 58% to 68%. In FY2024, FY2025 and the first half of 2026 it rose while days utilized slipped (by 0.8%, 2.9% and 5.9%), which reads as [E2-44]'s test met in a mild softening, after the fleet and the rig supply had been cut. On the eleven-year record the price was taken in two and a half years of tight or tightening supply and given in five of the six ample ones; that is not yet *\"an ability to increase prices rather easily\"*, and it is the fact the reversal condition turns on."),
("and I checked that the FY2025 rise in price per day came with falling utilization, the one year that reads the other way, and said so.",
 "and I checked the years that read the other way (FY2024, FY2025 and the first half of 2026, price up while days slipped) and set them in the first counter-argument and the reversal condition rather than leaving them out."),
("- **[E2-44] (2), growth with minor capital: not met.** Revenue growth from FY2008 to FY2014 came with capex of $175-387M a year against D&A of $115-230M, a fleet grown from 227 to about 330 robots, and then $1.5bn of equity written away.",
 "- **[E2-44] (2), growth with minor capital: not met.** Revenue growth from FY2008 to FY2014 came with capex of $175-387M a year against D&A of $115-230M and a fleet grown from 227 to 336 robots (*\"We have grown our ROV fleet size to 336 at 2014 from 304 at December 31, 2013\"*), which was then cut to 250 (*\"We have decreased our ROV fleet size over the last three years as a result of lower market demand.\"*, FY2017) while FY2018-FY2020 operating losses, impairments included, came to $882.3M."),
("(1) **ROV revenue per day utilized held or raised through a year in which contracted floating rigs and Oceaneering's ROV utilization both fall**, stated in a 10-K or 10-Q as price, not mix or geography, which is [E2-44]'s first characteristic shown in the one condition that tests it;",
 "(1) **ROV revenue per day utilized held or raised through a downturn of the FY2015-FY2020 kind (contracted floating rigs down by a fifth or more and Oceaneering's ROV utilization below 60%)**, stated in a 10-K or 10-Q as price, not mix or geography, which is [E2-44]'s first characteristic shown in the condition the last cycle failed; the mild softening of FY2024-FY2026 (rigs −6%, days −1% to −6%) already shows price taken and does not meet this;"),
("The 52% price recovery since 2020, the 35% returns of 2024-2025 on a written-down base,",
 "The 52% price recovery since 2020 (including price taken in FY2024, FY2025 and the first half of 2026 while days utilized slipped), the 35% returns of 2024-2025 on a written-down base,"),
]
for a,b in R:
    assert s.count(a)==1, a[:80]; s=s.replace(a,b)
open(p,'w',encoding='utf-8').write(s)
print('ok')
