"""Owner cash after every real cost for Apple (USD millions), from the filed cash-flow statements.
Owner cash = cash generated by operating activities - share-based compensation - payments for PP&E.
(OCF adds stock pay back; it is taken out again because stock pay is a real cost.)
Sources: 10-K FY2025 (0000320193-25-000079) for FY2023-FY2025; XBRL first-filed values for FY2016-FY2022
(10-Ks listed in facts_aapl.txt), FY2022 checked against the FY2022 10-K figures carried in facts_aapl.txt;
10-Q Q3 FY2026 (0000320193-26-000020) for the nine months."""

FY = {  # year: (OCF, SBC, capex, D&A)
    2016: (65824, 4210, 12734, 10505),
    2017: (63598, 4840, 12451, 10157),
    2018: (77434, 5340, 13313, 10903),
    2019: (69391, 6068, 10495, 12547),
    2020: (80674, 6829, 7309, 11056),
    2021: (104038, 7906, 11085, 11284),
    2022: (122151, 9038, 10708, 11104),
    2023: (110543, 10833, 10959, 11519),
    2024: (118254, 11688, 9447, 11445),
    2025: (111482, 12863, 12715, 11698),
}
NINE_26 = (116996, 10523, 6799, 9973)
NINE_25 = (81754, 9680, 9473, 8571)

def oc(t): return t[0] - t[1] - t[2]
def oc_da(t): return t[0] - t[1] - t[3]

print("year     OCF     SBC   capex     D&A   owner cash   (D&A variant)")
for y, t in FY.items():
    print(f"{y}  {t[0]:>7,} {t[1]:>7,} {t[2]:>7,} {t[3]:>7,}   {oc(t):>9,}   {oc_da(t):>9,}")
ttm = tuple(FY[2025][i] - NINE_25[i] + NINE_26[i] for i in range(4))
print(f"TTM to 2026-06-27: OCF {ttm[0]:,} SBC {ttm[1]:,} capex {ttm[2]:,} D&A {ttm[3]:,} -> owner cash {oc(ttm):,} (D&A variant {oc_da(ttm):,})")
five = [oc(FY[y]) for y in range(2021, 2026)]
mean5 = sum(five) / 5
print(f"five-year mean FY2021-FY2025: {mean5:,.0f}; D&A variant {sum(oc_da(FY[y]) for y in range(2021,2026))/5:,.0f}")
for a, b in ((2021, 2025), (2020, 2025), (2016, 2025)):
    g = (oc(FY[b]) / oc(FY[a])) ** (1 / (b - a)) - 1
    print(f"growth of aggregate owner cash FY{a}->FY{b}: {g*100:.2f}% a year")
