p = "Screens/_daily/OVERNIGHT LOG.md"
line = ("- 2026-09-28 20:08 | EGAN (eGain Corporation, cover 10-K 0001104659-26-106739) | Q1 IN / Q2 OUT "
"(on the business: every 10-K FY2002-FY2026 says \"Other than product innovation and existing customer relationships, "
"there are no substantial barriers to entry in this market\"; substitutes named include its own platform partners "
"(Five9, Genesys, Microsoft, Salesforce, ServiceNow), general-purpose AI and in-house builds; no filed year credits "
"revenue or margin to price and FY2026 records \"price reductions\"; cumulative operating income FY2003-FY2026 $0.5M on "
"$1,362M of revenue, one year above a 10.2% margin (FY2011); revenue $98.0M FY2023 to $91.1M, FY2027 guided to "
"$84.5-86.0M with a GAAP loss; [E4-04] on the business, not the perimeter close; case for IN written first; above "
"LivePerson, Upland and Five9, below Verint, NICE, Salesforce, ServiceNow and Pegasystems) | $5.67 (2026-09-28 Nasdaq "
"close, aggregator, flagged; regularMarketTime 16:00:01 ET, 235,262 shares traded) x 26,171,467 sh (one class, 5M "
"preferred authorized none issued; 1-for-10 reverse split 2003) = cap $148.4M, cash $73.3M, no debt; sovereign 5.56% "
"(UST 30Y par 09/28/2026, direct fetch, the tool agreed) | FAIL (Q2) | 218209f7 12079a70 9faf58fe f1a6c6c8 029160a7 "
"d2cd76ec | WAVE 7 name 106 of 218, register entry 248 (dispatcher re-counted from the file: heading unique at line "
"502, 248 entries to the write-early heading, EGAN first and once, CW second; done file 106 lines equal to the order "
"file's first 106; no alert and no PORTFOLIO row; reading-list fold ends \"Next in the order file: TECH.\"; "
"check_framework PASS re-run by the dispatcher). EGAN in no tier roster. Deal: none live (the one Item 1.01 is a "
"director indemnification agreement; Kanen below 5% 2025-11-13; JPMorgan warrant for 500,000 sh at $7.10 with a "
"board observer; founder 33.7%). Below the close, computation only: five-year owner earnings $4.11-4.21M (2.77-2.84% "
"of cap), stock compensation 55.7% of OCF FY2022-26, FY2026 flattered by an $8.03M receivables collection. Screen "
"errors: cap_m 35.5% high (FY2025 count at a late-August close); wc_note arithmetic reproduces (48.2%), refuted as a "
"warning (the SaaS billing build stopped, never reversed); yields on the stale cap and 5.35%; best_year_note refuted "
"both halves; level_note truncated and understated; newest_filing and newest_periodic stale; acq_note, da_note, "
"deal_note right. Brief error: eGain is Delaware-incorporated. REPORTED, NOT PATCHED: NEW, run.py took FY2020-FY2022 "
"as its three-year window on a FY2026 filer and printed a positive points-over beside a yield below the bond; NEW, "
"sources.cik_for returned no CIK for VRNT or LPSN; deal_note TypeError and ValueError again; chartPreviousClose 2.97 "
"meaningless. Agent's own errors recorded in the run file, all corrected before commit. Left on disk uncommitted: the "
"ignored cache/, the agent's scratch _msg.txt, and the pre-existing ARCB _logmsg_dispatch.txt, not touched. "
"112 remain. Next: TECH.\n")
with open(p, "a", encoding="utf-8", newline="") as f:
    f.write(line)
print("ok")
