p=r'C:\Users\chreh\OneDrive\Documents\BRK\Test Runs\2026-10-06 Run - LRN Stride.md'
t=open(p,encoding='utf-8').read()
R=[
("Margin of safety is an attitude here\nand arithmetic only at Q7 **[M1996-084]**. No macro forecast enters **[M2000-094]**: the",
 "Margin of safety: \"if you have to actually do it on — with pencil and paper, it’s too close to think about\"\n**[M1996-084]**; the arithmetic belongs to Q7. No macro forecast: \"macro conclusions are — just never enter into the\ndiscussion\" **[M2000-094]**; the"),
("not used as a forecast. Who is paid to tell you **[M2020-037]**: the filer",
 "not used as a forecast. Who is paid to tell you: \"you do not get impartial advice from Wall Street\" **[M2020-037]**; the filer"),
("A purchase for cash, unlevered, sized so that a total loss could be borne, puts no buyer at risk of ruin **[M2012-081]**,\n**[L2023-005]**. Nothing about the target changes that; the rule is met by the buyer's conduct.",
 "A purchase for cash, unlevered, sized so that a total loss could be borne, keeps the buyer inside \"We are never going to\nrisk what we have and need for what we don’t have and don’t need.\" **[M2012-081]** and \"Never risk permanent loss of\ncapital.\" **[L2023-005]**. Nothing about the target changes that; the rule is met by the buyer's conduct."),
("- **The key variables** **[M1998-044]**: (a)",
 "- **The key variables**, \"trying to identify the key variables in that particular business, and evaluating how\n  predictable they were first\" **[M1998-044]**: (a)"),
("costs ran 62.2% to 66.6% of revenue FY2017-2026)","costs ran 60.8% to 66.6% of revenue FY2017-2026)"),
("can be read from the filings\n  **[M2012-065]** (\"where the company will stand within the industry\").",
 "can be read from the filings:\n  \"where the company will stand within the industry\" **[M2012-065]**."),
("castle's permanence is the Q1/Q2 line; the rows place the sustainable edge after\n  the first filter **[M1997-148]**, and the Q2 text owns \"what could destroy, modify or reduce\" **[M2000-014]**. I take it\n  to Q2 and say so in the last section.",
 "castle's permanence is the Q1/Q2 line. The rows put the edge after the first filter: \"if it passes through that, it’s\n  whether a company can have a sustainable edge\" **[M1997-148]**; and the risk to the castle is asked as what will\n  \"destroy, or modify, or reduce the economic strengths\" **[M2000-014]**, which the framework places at Q2. I take it to\n  Q2 and say so in the last section."),
("- **Doubt rule** **[M2002-092]**: my doubt","- **Doubt rule**, \"if you have doubts about something being into your circle of competence, it isn’t.\" **[M2002-092]**:\n  my doubt"),
("Pearson, the only national rival with an SEC filing, runs 41 schools)","Pearson, named first among Stride's competitors in its 10-K and the one rival with an SEC filing, runs 41 schools)"),
("3. **The money test** **[M2011-015]**.","3. **The money test**: \"if I had a hundred million dollars and I wanted to go in and take on See’s Candy, could I do it?\"\n   **[M2011-015]**."),
("Agora\n   (2012 notice; the largest managed school then) and","Agora\n   (2012 notice) and"),
("Pearson, a group with £3,577M of 2025 sales, has run Connections Academy for the whole\n   span and holds 41 schools in 31 states (20-F 2025), about a quarter of Stride's school count; it has not displaced\n   Stride, and Stride has not displaced it.",
 "Pearson (Connections Academy, named in Stride's 10-K), a group with £3,577m of 2025 sales, holds 41 schools in 31\n   states with Virtual Learning sales of £511m (20-F 2025), against Stride's 92 General Education schools and $2,461.5M\n   of K-12 revenue (10-K FY2026); it has not displaced Stride, and over 2019-2025 Stride has not displaced it."),
("4. **Pricing power and the agony before a rise** **[M2005-020]**.","4. **Pricing power**: \"you can almost measure the strength of a business over time by the agony they go through in\n   determining whether a price increase can be sustained\" **[M2005-020]**."),
("5. **Unit volume and share of mind** **[M1997-099]**.","5. **Unit volume and share of mind**: \"It’s share of mind. It’s not share of market.\" **[M1997-099]**."),
("the board, which holds the charter, stands where the retailer stands in\n   **[M2001-090]**: the value can move to whoever holds the charter.",
 "the board, which holds the charter, stands where the retailer stands in \"the value of having the brand moves over to\n   the retailer from the product itself\" **[M2001-090]**."),
("while instructional cost stayed at 62% to 67%:","while instructional cost stayed at 61% to 67%:"),
("8. **Would the customer still choose it over the low bid** **[M2017-009]**.","8. **The low bid**: \"it wouldn’t be a question of people buying candy for the low bid\" **[M2017-009]**."),
("10. **Widening or narrowing** **[M1999-108]**, over","10. **Widening or narrowing**, \"whether it’s likely to widen further or shrink on you\" **[M1999-108]**, over"),
("11. **What could destroy, modify or reduce it** **[M2000-014]**.","11. **What could \"destroy, or modify, or reduce the economic strengths\"** **[M2000-014]**."),
("\"A great company is one that's going to remain great for 30 years. If it's going to be a great company for\nthree years, you know, it ain't a great company.\" **[M1996-054]**",
 "\"a great company is one that’s going to remain great for 30 years. If it’s going to be a great company for\nthree years, you know, it ain’t a great company.\" **[M1996-054]**"),
("NATURE, not WORK. The test is whether the deciding question is a forecast the insiders would write\ndown **[M2000-105]**.",
 "NATURE, not WORK. The test is whether the industry's insiders would \"put down on paper their predictions\"\n**[M2000-105]** of the deciding question."),
("so a research pass would end unsure, and \"a pass that ends unsure ends TOO HARD (NATURE)\" (section I; **[M2002-092]**).",
 "so a research pass would end unsure, and section I sends a pass that ends unsure to TOO HARD (NATURE)."),
("### The balance sheets, FY2011 to FY2026 (what the Q4 rule would read first **[M2025-032]**)",
 "### The balance sheets, FY2011 to FY2026 (\"balance sheets over an 8 or 10 year period before I even look at the income account\" **[M2025-032]**)"),
("Stock pay $40.3M (FY2026) is excluded from every \"adjusted\" figure the filer leads with; the speakers' line on that habit is\n**[L2016-006]** and **[L2015-003]**, and the filer's releases feature \"EBITDA\" and \"Adjusted EBITDA\" **[M2002-026]**.",
 "Stock pay $40.3M (FY2026) is excluded from every \"adjusted\" figure the filer leads with: \"wave away very real costs\"\n**[L2016-006]**; stock pay is \"the most egregious example\" **[L2015-003]**; and the releases feature \"EBITDA\" and\n\"Adjusted EBITDA\", against \"where people are talking about EBITDA, is going to be about zero\" **[M2002-026]**."),
("30.9% a year, from a low base year **[L2005-003]**; carried ten\n  years it would put owner cash at about $3.8bn, above the whole of FY2026 revenue, an absurdity under Q3's cap.",
 "30.9% a year, from a low base year (\"a base year in which earnings were poor can produce a breathtaking, but\n  meaningless, growth rate\" **[L2005-003]**); carried ten years from the five-year mean it would put owner cash at about\n  $2.5bn, the whole of FY2026 revenue, an absurdity under Q3's cap."),
("that would close\n  OUT at Q7 (not a screamer **[M2009-005]**), had Q7 been reached.",
 "that would close\n  OUT at Q7, had Q7 been reached, since it does not \"scream at you\" **[M2009-005]**."),
("- **Whole-cycle variant** (the five-year window holds the four best years of fifteen):","- **Whole-cycle variant** (the five-year window holds the five best years of fifteen):"),
("- **Tax and base.** The floor (CONVENTION, Q7) is about ten percent pre-tax **[M2003-149]**.",
 "- **Tax and base.** The floor (CONVENTION, Q7) is about ten percent pre-tax, after \"we don’t want to buy equities where\n  our real expectancy is below 10 percent\" **[M2003-149]**."),
("so no pencil is needed on which regime returns **[M1996-084]**.","so no pencil is needed on which regime returns (\"if you have to actually do it on — with pencil and paper, it’s too\n  close to think about\" **[M1996-084]**)."),
("- None of the three figures reopens the file: a TOO HARD (NATURE) is not reopened by price **[M2000-038]**.",
 "- None of the three figures reopens the file: \"It doesn’t mean it isn’t a good buy. It doesn’t mean it isn’t selling for a\n  fraction of its worth. It just means that we don’t know how to evaluate it.\" **[M2000-038]**"),
("about the bottom of the computed range ($80.88)\n  and above the fair price ($61.76) and the whole-cycle top ($89.39) by turns;",
 "about the bottom of the computed range ($80.88),\n  above the fair price ($61.76) and below the whole-cycle top ($89.39);"),
("Q1's definition asks for \"a reasonable fix\non ... earning power\" **[M2012-065]**, which I could not get; Q2 owns \"what could destroy, modify or reduce\" **[M2000-014]**\nand sends an unjudgeable castle to TOO HARD.",
 "Q1's definition asks for \"a reasonable fix\non about what the earning power and competitive position will look like\" **[M2012-065]**, which I could not get; Q2\nasks what will \"destroy, or modify, or reduce the economic strengths\" **[M2000-014]** and sends an unjudgeable castle to\nTOO HARD."),
("I passed Q1 on the economic\ndynamics **[M2011-014]** and closed at Q2,","I passed Q1 on \"the economic\ndynamics of the industry\" **[M2011-014]** and closed at Q2,"),
("Section I tests the cause by whether insiders would write the forecast down **[M2000-105]**;",
 "Section I tests the cause by whether insiders would \"put down on paper their predictions\" **[M2000-105]**;"),
]
for a,b in R:
    if a not in t: print("NOT FOUND:",a[:90].replace('\n','/')); continue
    t=t.replace(a,b,1)
open(p,'w',encoding='utf-8').write(t)
print('done')
