import sys
ts = sys.argv[1]
line = ("- " + ts + " | WING (Wingstop Inc., cover 10-Q 0001628280-26-050580) | Q1 IN / Q2 OUT (on the business: [E3-43] pricing half not demonstrated, no system menu price or price/transaction split filed 2015 prospectus to the 2026 10-Qs, search recorded; company-restaurant food cost ratio moved with the filer's wing cost twelve of twelve years FY2013-FY2024, FY2021 35.9% to 44.8% on 40.9% wing inflation; [E3-03] criterion (2) fails in the filer's words, competes on \"price, service, value\", \"higher prices could adversely affect transactions\"; first falling period in 21 years, domestic SSS -3.3% FY2025 and -8.1% H1 2026, answered with \"investments in value\" while El Pollo Loco grew 4.9%; McDonald's distinguished, no land or rent held; SSS up every year 2004-2024 and +106.6% compounded 2019-2025 against 21.7-31.2% at four filed peers written first as the strongest evidence against; reversal condition in words) | $99.07 (2026-09-25 Nasdaq close, aggregator, flagged; a $100.17 intraday print recorded, not used) x 27,242,546 sh (one class, no preferred issued) = cap $2,698.9M; sovereign 5.49% (UST 30Y par 09/25/2026, struck fresh) | FAIL (Q2) | 99e6c78b 99869c65 baf744b0 bea6983d 9ca1cfd5 | "
 "WAVE 7 name 97 of 218, register entry 239 (dispatcher re-counted from the file: heading unique, 239 entries to the write-early heading, WING first; done file 97 lines equal to the order file's first 97; no alert and no PORTFOLIO row; reading-list fold ends \"Next in the order file: SANM.\"; check_framework PASS re-run by the dispatcher). WING in no tier roster. No live deal: Wingstop the buyer of 13 restaurants for $32M. "
 "Beneath the close, computation only: owner earnings $34.8-109.6M every window FY2013-FY2025 at both (c) ends (1.29-4.06% of cap), TTM $106.4-140.8M (3.94-5.22%), none reaching 5.49%; FY2025 carries a $35.9M deferred-tax benefit; 2020 notes $472.8M due December 2027. #20 THE WAVE with #5 as a feature, signatures only, dated note. "
 "Screen errors: cap_flag resolved as two dates (float struck at $347.61 on 2025-06-27, stock down 71.5%), neither figure wrong; cap_m 13.8% high; yield fields on the stale cap and 5.35%; \"9-yr OCF series\" refuted, thirteen tagged; acq_note misses $10.8-18.5M a year of franchisee restaurant purchases FY2023-25. oe_bottom/oe_top and the level step confirmed. "
 "REPORTED, NOT PATCHED: tools/sources.price and tools/run.py again took an intraday print with no market-open warning (second filer); points_over() growth struck against the bond not the floor (fourth filer). Agent's own errors (a sensitivity compound, a food-cost ratio, a release date, four unsupported claims, one non-verbatim quotation) corrected before commit. Left on disk uncommitted: the agent's _msg.txt and the ignored cache/. 121 remain. Next: SANM.\n")
with open("Screens/_daily/OVERNIGHT LOG.md", "a", encoding="utf-8", newline="\n") as f:
    f.write(line)
