import io, os
p = os.path.join(os.path.abspath("."), "Screens/_daily/OVERNIGHT LOG.md")
s = io.open(p, encoding="utf-8").read()
assert "| CB |" not in s, "a CB line is already in the overnight log"
LINE = ("- 2026-09-19 15:31 EDT | CB | **Q1 IN / Q2 IN (NARROW) / Q3 IN (binary gate) / Q4 IN / Q5 NOT IN - quit on at the ~10% [E4-28] floor, FAIL ON PRICE.** "
        "WAVE 6 and the MINI BERK insurance track, run under the sector method with both amendments applied; CIK 0000896159 found by cik_for(), the registrant "
        "being the former ACE Ltd renamed 2016-01-15 after buying The Chubb Corporation. **The first name in this queue to pass the MKL test outright:** the "
        "CURRENT-ACCIDENT-YEAR combined ratio INCLUDING catastrophes was 92.6 / 97.9 / 93.9 / 93.4 / 97.4 / 91.9 / 90.4 / 88.6 / 88.7 / 88.2 for 2016-2025 - "
        "**below 100 in ten of ten years, worst 97.9 in the Harvey-Irma-Maria year, ten-year mean 92.3** - so the reported underwriting profit is earned, not "
        "released (2025 releases $1,132M of $6,528M, 17%); built TWICE and the second construction is not the filer's, agreeing within 0.3 points every year. "
        "Favourable PPD in all ten years and declining, 4.3 to 2.5 points. Expense ratio 28.5 (2018) to a 25.6 trough (2022) and back up 1.0 point to 26.6, all "
        "in policy acquisition - the MKL shape 9.5 points lower and half the slope, recorded as a Q6 item not a Q2 failure. **Peer row EXTENDED from the MKL run, "
        "not rebuilt, onto the current-accident-year basis, and the ranking CHANGES: KNSL 80.60 > ACGL 86.99 > CB 89.50 > WRB 89.84 > RLI 93.08 > AXS 94.10 > MKL "
        "100.27, where the reported basis had RLI third and CB fourth - RLI's headline 85.52 is 6.1 to 10.8 points of releases a year.** AXS inverts (2023 "
        "reported 99.9 held 8.1 points of ADVERSE development); **WRB is the row's reserving-integrity benchmark at ~zero net development three years running on a "
        "$10-12bn book**; FFH NOT COMPARABLE (IFRS 17); KNSL 2021 and RLI 2021 named as unobtainable, not estimated. Q2 NARROW on four recorded defects: [E3-03] "
        "criterion 3 **fails outright** for the 5.3% of premium in the federal crop programme where *all approved providers offer the same product forms and "
        "rates* ([E2-59], carried as the BRK run carried BHE); **[E2-44] fails on its first half in the filer's own words** (rate decreases in Large Risk and E&S "
        "property, Major Accounts +1.4%, softness spreading to casualty in Q2 2026) - Chubb shrinks rather than raises price, which is [E4-37] detecting a "
        "downgrade in real time; no untapped pricing power; **key-person dependence recorded AT Q2 [E4-23]** (22 years, no named successor, 17.7% against the "
        "chairmanship in 2026 and 22.6% in 2025). Q3 a gate on daily execution [E2-70, E2-50] and leverage (investments 2.29x equity); **[E4-29] clean and tested "
        "the hard way - grep -ic ebitda = 0 in both proxies, all four EX-99.1 releases, all four EX-99.2 supplements and all four 8-K bodies**; three flags fired "
        "and do NOT converge [E4-52] - the quarterly *double-digit growth in EPS and tangible book value* promise plus a *14% plus* medium-term ROE target "
        "([E5-30]'s ratchet, but [E3-48]'s action taken and the promises BEATEN: TBVPS +17.1% y/y, core operating ROE 14.5%), the FY2025 **leverage-ratio "
        "redefinition** excluding unrealised losses (18.85% to 18.44%, announced with reasons and the prior year restated, which is [E2-49]'s candor case), and "
        "an acquisition every year ([E2-30](2); goodwill+intangibles+VOBA $29,423M = 40% of equity, all inside insurance); [E4-30] REFUTED on both halves "
        "(10.4-point combined-ratio range, net income -38% in 2022; the 5.4% 2023 tax rate is the named Bermuda ETA asset and the rate has risen since); [E2-52] "
        "cleared by reading the Swiss capital-contribution-reserve routing rather than grepping it. **[E2-67] SATISFIED with three things recorded against it**: "
        "from the nine triangles' own supplementary lines, 2025 PPD is workers' comp $(519)M against NA Commercial Liability +$319M and Other Casualty +$162M "
        "adverse plus $306M of run-off, so **long-tail net is only $(61)M and 95% of the favourable development is SHORT-TAIL**; the error runs in TWO directions "
        "(short-tail conservatively over-reserved ten years running; **NA long-tail casualty adverse in eight of the last nine accident years**, AY2018 +18.7%, "
        "AY2019 +16.5%, AY2023 +8.8% in two years, IBNR 52-71% of incurred); against it, the filer calls its own triangles *of limited use for independent "
        "analysis*, publishes no consolidated scorecard of its own error, and the actuarial function reports to the CFO - mitigated by an annual **external "
        "independent actuarial assessment** reviewed by an all-independent Audit Committee; **[E2-72] is the one candor item not cleared: no shareholder letter**. "
        "**[E4-27] is the sharpest finding and was NOT in the brief: 100% of the CEO's equity vests on TBVPS growth (70%) and the REPORTED P&C combined ratio "
        "(30%), with no catastrophe and no prior-development exclusion in the PSU criteria - the incentive aimed at the pen [E2-50] - and the decisive counterweight "
        "is the row itself: the metrics are RELATIVE and Chubb releases LESS than every peer but WRB.** CAPITAL-ALLOCATION FLAG LIVE [E5-08](2): buybacks at "
        "1.43x/1.69x/1.50x year-end book 2023-25 and 2.5x tangible book in H1 2026, **no published repurchase condition** where [E5-25] shows Berkshire "
        "publishing both as numbers. Q4: **no owner-earnings number computed, and the LOEWS TEST was run explicitly and its answer discarded** - OCF less SBC is "
        "9.45% of the cap and falls to 4.75% once $3,402M of reserve growth and $2,775M of unearned-premium growth are stripped, a 50% collapse. **Cost of float "
        "[E3-69] -6.61 / -7.82 / -9.08 / -9.24 / -9.82%, five-year mean -8.58% on average float of $60,823M, against BERKSHIRE'S -3.6% on the identical five "
        "years** - diagnostic, nothing added. Stage 0(b) both ratios: **float/investments 40.3%, almost exactly [E5-46]'s own 41.8% calibration (so step 2 is a "
        "MAJOR term here, unlike WTM's 22.0%); investments/equity 2.29x, ABOVE Markel's 2.01x and five times Berkshire's 0.45x**, so CONVENTION 5 binds. [E4-20] "
        "GOOD not great, [E4-43] governs; [E5-11] 3 of 3 with $4.8bn of [E5-39] funding named ($3.3bn of repos all inside five months; a bank pooling programme "
        "in which *Chubb entities may incur overdraft balances*, guaranteed to $1,500M). **Death named and quantified: not the catastrophe** (1-in-250 worldwide "
        "aggregate $9,285M = 12.6% of equity, about one year's pre-tax operating income) **but the reserve cushion and the price cycle stopping together** - "
        "workers' comp redundancy entirely in accident years 2016-20 and absent in 2021-24, NA casualty draining $481M a year, long-tail net $110M from flipping, "
        "the filer's own four *reasonably likely* deviations summing to $2,764M; modelled, combined ratio 85.7 to 92.6 and pre-tax operating $12,000M to $8,875M "
        "- **a real possibility, and a RETURN event not a survival event**. [E4-40] turned on the filer's own model: realised cats averaged $2,308M on a book 58% "
        "smaller at the start, scaling to ~$3.3bn, **at or above the modelled 1-in-10 of $3,003M** (population mismatch stated). Shape **#7 with #11 as a feature, "
        "and #23 THE CUSHION proposed** pending the operator. Q5: four windows published [E4-38], pre-tax operating yield **9.13% / 8.22% / 7.11% / 6.21%** (a "
        "2.92-point spread), needing 0.87 to 3.79%/yr forever to reach ~10%; **one [E4-41] windage gives about 7% normalised**; after tax 5.7-7.9% shown; value "
        "**~$235 / $275 / $310 against $340.64**, above the whole range, screamer test NO, windage count 1. **The two-component sum ($412-$537) is REPORTED and "
        "NOT USED, with the reconciliation stated: $174 of the $302 component 1 is float that is not deducted, and at 2.29x that convention manufactures 1.6x book "
        "where at Berkshire's 0.45x it produces less than book - the exact collision step 4 was corrected for on 2026-09-02 by the BRK run.** [E3-71] deferred tax "
        "**nil** (the AFS book carries a $2,046M unrealised LOSS). [E5-50] third element mildly positive, stated not numbered: [E3-54] passes at $1.50 per $1 "
        "retained, but 6.6 of the 15.19 points of annual return came from the multiple going 1.20x to 1.66x book. **Six brief/method/tooling defects**, the "
        "sharpest being that **the sector method's step 1 has no rule for non-float funding that is not free** - at Chubb, debt, repos and the life/annuity "
        "liabilities are worth $142 a share and the deduction is confessed as this run's own judgment. **Register entry 123, counted inside the fold script before "
        "and after (122 then 123, exactly one added, no duplicate).** | **US$340.64** (2026-09-18 close, tools/sources.py, aggregator flagged) x **385,799,859** "
        "Common Shares (Q2 2026 10-Q COVER, accession 0000896159-26-000017, *outstanding as of July 20, 2026*; the Swiss trap tested by arithmetic - 400,120,847 "
        "issued vs 385,634,049 outstanding at 6/30/26, a 14,486,798-share treasury gap, so the cover IS net of treasury and the issued figure would have "
        "overstated the cap by $4,879M) = cap **US$131,419M**; sovereign **5.34% USD** (US Treasury 30Y par, 09/18/2026, struck fresh, not FRED; multi-currency "
        "gap disclosed as UNRESOLVED per the sector method's FINDING 8, 40.7% of premium earned abroad, with the direction of the error stated) | "
        "**FAIL at Q5 on price**; check_framework PASS | see fold commit. Bands armed $310 and $255; PORTFOLIO watch row added; CB struck in the WAVE 6 table and "
        "added to the MINI BERK roster. Concurrent BLK, USAR and ERIC files left untouched\n")
io.open(p, "w", encoding="utf-8", newline="\n").write(s.rstrip("\n") + "\n" + LINE)
print("overnight log line appended")
